### ISSUE TITLE
test/stability/testSingleWorkingFF/ fails with gotest

### ISSUE THREAD

**Issue by dkolistratova** [intel-go/nff-go#325] opened 2018-05-03 15:28 UTC
Packet contents are incorrect
Test generated a number of packet which exceed planned two times
panic: runtime error: index out of range

goroutine 235 [running, locked to thread]:
github.com/intel-go/nff-go/test/stability/testSingleWorkingFF.commonCheck(0x7f013da26d40, 0x531001)
        /localdisk/newProj/src/github.com/intel-go/nff-go/test/stability/testSingleWorkingFF/testSingleWorkingFF.go:513 +0x5f8
github.com/intel-go/nff-go/test/stability/testSingleWorkingFF.checkInputFlow2(0x7f013da26d40, 0x0, 0x0)
        /localdisk/newProj/src/github.com/intel-go/nff-go/test/stability/testSingleWorkingFF/testSingleWorkingFF.go:465 +0x2f
github.com/intel-go/nff-go/flow.handle(0x7f013da26d40, 0xc4214a0380, 0x0, 0x0, 0x0)
        /localdisk/newProj/src/github.com/intel-go/nff-go/flow/flow.go:1245 +0x47
github.com/intel-go/nff-go/flow.segmentProcess(0x71d520, 0xc4214d02e0, 0xc421628420, 0xc421628480, 0xc423bfe600, 0xc4215140f0, 0x3, 0x3)
        /localdisk/newProj/src/github.com/intel-go/nff-go/flow/flow.go:960 +0x58f
github.com/intel-go/nff-go/flow.(*scheduler).startFF.func1(0xc423c001e0, 0x4)
        /localdisk/newProj/src/github.com/intel-go/nff-go/flow/scheduler.go:210 +0x24c
created by github.com/intel-go/nff-go/flow.(*scheduler).startFF
        /localdisk/newProj/src/github.com/intel-go/nff-go/flow/scheduler.go:204 +0x253
exit status 2
FAIL    github.com/intel-go/nff-go/test/stability/testSingleWorkingFF   116.341s

just run make testing

**Comment by ifilippov** [comment] 2018-05-03 15:56
I suppose that it is a test problem. Can you please make sure that test understand totalNumber in correct way?

**Comment by ifilippov** [comment] 2018-05-03 20:16
Can't reproduce this. Can you please try one more time? (I committed generate fix)

**Comment by dkolistratova** [comment] 2018-05-04 10:26
failed at commit 00e6475f2b8a54b5edff256da33966c8356af3af
but now it does not. Seems like some of last commits  fixed.

**Comment by ifilippov** [comment] 2018-05-04 12:05
Please, find exact reason and place it here.

**Closed** 2018-05-10 10:32 UTC
