### ISSUE TITLE
Creating a proper and repeatable build environment

### ISSUE THREAD

**Issue by juey90** [intel-go/nff-go#441] opened 2018-08-03 12:31 UTC
Hi guys, first i would like to thank you for the amazing toolkit you created for easily building fast packet processing apps in go.

The problem i have is to set up a build environment using nff-go with your documentation and my IDE, i am having a hard time getting cgo to work. 
It says: 
`cc1: fatal error: rte_config.h: No such file or directory`

I can compile my code using your examples directory and `make`, i´ve looked at the makefiles and copied the CFLAGS and LDFLAGS in my IDE as environment variables but i always encounter that error.

- Goland 2018.2 IDE
- `$ go version`
`go version go1.10.3 linux/amd64`
- OS is Fedora 28 with 
`$ uname -r`
`4.17.7-200.fc28.x86_64`
- Checked out the master branch of nff-go and compiled the including dpdk (18.02)
- Followed your docs, executed the prerequieries script etc.

Thanks for help

**Comment by gshimansky** [comment] 2018-08-03 20:55
To successfully run `go build` command outside of NFF-Go source tree you need to set

- `RTE_SDK`
- `RTE_TARGET`
- `CGO_CFLAGS`
- `CGO_LDFLAGS`
- and maybe `CGO_LDFLAGS_ALLOW`

environment variables in a way that they are initialized in `mk/include.mk` file. Try to add `echo` after `export` statements to print variables values so that you could copy them into your IDE.

**Comment by gshimansky** [comment] 2018-08-07 14:29
Yes, I doubt it is possible to use anything other than absolute paths in these variables. Go compiler definitely doesn't support any variables in its values.

Closing because the problem is resolved.

**Closed by gshimansky** 2018-08-07 14:29 UTC
